pull_request_rules:
  - name: Automatic merge for pre-commit.ci
    conditions:
      - author~=^pre-commit-ci\[bot\]$
      - check-success=Actions/Lint (pull_request)
    actions:
      merge:
        method: rebase
