pull_request_rules:
  - name: Automatic merge for pre-commit-ci
    conditions:
      - author=app/pre-commit-ci
      - base=main
      - check-success="pre-commit.ci - pr"
      - check-success="Lint"
      - check-success="CodeQL"
      - check-success="Dependency review"
      - -draft
    actions:
      merge:
        method: rebase
        strict: true
      delete_head_branch: true
