name: Auto-merge pre-commit-ci PRs

on:
  pull_request:
    types: [opened, synchronize, ready_for_review]

permissions:
  pull-requests: write
  contents: write

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Information
        run: |
          echo "Actor: ${{ github.actor }}"
          echo "Event: ${{ github.event_name }}"
          echo "Action: ${{ github.event.action }}"

  auto-merge:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'pre-commit-ci[bot]' }}
    steps:
      - name: Enable auto-merge
        run: gh pr merge --auto --rebase --delete-branch "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
