name: Auto-approve Renovate PRs

on:
  pull_request:
    types: [opened, synchronize, ready_for_review]

permissions:
  pull-requests: write
  contents: write

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    if: >-
      ${{ github.actor == 'renovate[bot]'
      || github.event.pull_request.user.login == 'renovate[bot]' }}
    steps:
      - name: Approve PR
        run: |
          gh pr review "$PR_URL" --approve \
            -b "Automatically approved Renovate bot updates"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
