---
name: "Dependency review"
on: [pull_request]

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v3.5.1
      - name: "Dependency Review"
        uses: actions/dependency-review-action@v3.0.4
        with:
          comment-summary-in-pr: true
